"""Atualização do app/models.py, inclusão dos campos data de nascimento  e data de registro

Revision ID: cc41754e11e3
Revises: 
Create Date: 2025-10-02 20:44:59.225541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc41754e11e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('data_registro', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('data_registro')
        batch_op.drop_column('data_nascimento')

    # ### end Alembic commands ###
